Task/feature 3 new
ozonmp/rcn-product-api pull request #2
Opened 2021-11-02 09:27 UTC by MariaSopkova

Реализация задачи 3

2021-11-03 19:47 UTC, LiFeAiR requested changes
+ поправь замечания от `GitHub Actions / lint`

2021-11-03 19:47 UTC, LiFeAiR commented on api/ozonmp/rcn_product_api/v1/rcn_product_api.proto
> +      get: "/v1/create"
по моему тут должен быть метод `post`

2021-11-03 19:47 UTC, LiFeAiR commented on api/ozonmp/rcn_product_api/v1/rcn_product_api.proto
> +      get: "/v1/remove/{product_id}"
по моему тут должен быть метод `delete`

2021-11-03 19:47 UTC, LiFeAiR commented on api/ozonmp/rcn_product_api/v1/rcn_product_api.proto
> +      get: "/v1/list"
по моему метод должен называться `products`

2021-11-03 19:47 UTC, LiFeAiR commented on examples/create_test.sh
> +  "foo": "test"
тут все таки реальные данные для создания сущности должны быть
```
message Product {
   uint64 id = 1;
   string title = 2;
   string description = 3;
   float rating = 4;
 }
```

2021-11-03 19:47 UTC, LiFeAiR commented on examples/remove_test.sh
> +echo "id = 4"
зачем это?

2021-11-03 19:47 UTC, LiFeAiR commented on examples/remove_test.sh
> +echo "id = -1"
зачем это?

2021-11-03 19:47 UTC, LiFeAiR commented on examples/remove_test.sh
> +echo "without id"
ну ок)
это выглядит как консольные комментарии к тесту

2021-11-03 19:47 UTC, LiFeAiR commented on internal/repo/repo.go
> +	"github.com/ozonmp/rcn-product-api/internal/model/db"
сортировка импорта?

2021-11-04 09:09 UTC, MariaSopkova commented on examples/remove_test.sh
> +echo "without id"
Задание 7 :)

2021-11-04 09:28 UTC, MariaSopkova commented on api/ozonmp/rcn_product_api/v1/rcn_product_api.proto
> +      get: "/v1/create"
согласна

2021-11-04 09:28 UTC, MariaSopkova commented on api/ozonmp/rcn_product_api/v1/rcn_product_api.proto
> +      get: "/v1/remove/{product_id}"
да

2021-11-07 17:29 UTC, LiFeAiR approved these changes

2021-11-10 11:34 UTC, merged