Task/feature 4
ozonmp/rcn-product-api pull request #3
Opened 2021-11-10 11:35 UTC by MariaSopkova

2021-11-12 17:35 UTC, LiFeAiR requested changes

2021-11-12 17:35 UTC, LiFeAiR commented on api/ozonmp/rcn_product_api/v1/product_event.proto
> +
поправь замечания линтера `GitHub Actions / buf-lint`

2021-11-12 17:35 UTC, LiFeAiR commented on docker-compose.yaml
> +  #nginx:
зачем закомментировала?

2021-11-12 17:35 UTC, LiFeAiR commented on internal/repo/repo.go
> +		"product").Where(sq.NotEq{"removed": false}).OrderBy("title").Limit(limit).Offset(cursor)
`sq.NotEq{"removed": false}`
только удаленные?

2021-11-12 17:35 UTC, LiFeAiR commented on migrations/000001_init_db.sql
> +CREATE UNIQUE INDEX PRODUCT_ID_UINDEX
BIGSERIAL уже дает уникальный кластерный первичный индекс

2021-11-12 17:35 UTC, LiFeAiR commented on migrations/000001_init_db.sql
> +    ID BIGSERIAL,
сюда добавь `PRIMARY KEY`

2021-11-12 17:35 UTC, LiFeAiR commented on migrations/000001_init_db.sql
> +    ID BIGSERIAL,
сюда добавь `PRIMARY KEY`

2021-11-12 17:35 UTC, LiFeAiR commented on migrations/000001_init_db.sql
> +        PRIMARY KEY (ID);
а это удали

2021-11-12 17:35 UTC, LiFeAiR commented on partitions.sql
> +do $$
партиции нужны для какой задачи?

2021-11-12 17:40 UTC, LiFeAiR requested changes

2021-11-12 17:40 UTC, LiFeAiR commented on cmd/grpc-server/main.go
> +	db, err := database.NewPostgres(&cfg, cfg.Database.Driver)
посмотри строчку `if *migration {`
она же никогда не выполнится?

2021-11-12 17:49 UTC, LiFeAiR commented on internal/repo/repo.go
> +			tx.Rollback() //nolint:errcheck
не очень хорошая идея прятать ошибку которая может возникнуть при ролике
хотя бы залакируй ее

2021-11-12 20:20 UTC, MariaSopkova commented on internal/repo/repo.go
> +		"product").Where(sq.NotEq{"removed": false}).OrderBy("title").Limit(limit).Offset(cursor)
Наоборот. Не удаленные. NotEq

2021-11-12 20:22 UTC, MariaSopkova commented on partitions.sql
> +do $$
Задача с алмазиком. Думаю суть была просто научиться их делать

2021-11-15 14:50 UTC, LiFeAiR commented on internal/repo/repo.go
> +		"product").Where(sq.NotEq{"removed": false}).OrderBy("title").Limit(limit).Offset(cursor)
тогда надо писать `sq.Eq{"removed": false}`

2021-11-15 14:55 UTC, LiFeAiR commented on internal/repo/repo.go
> +type ProductUpdating struct {
поправь замечание лихтера

2021-11-15 20:05 UTC, LiFeAiR approved these changes

2021-11-17 06:41 UTC, merged