Task/feature 5
ozonmp/rcn-product-api pull request #4
Opened 2021-11-17 18:55 UTC by MariaSopkova

2021-11-18 18:43 UTC, LiFeAiR requested changes

2021-11-18 18:43 UTC, LiFeAiR commented on docker-compose.yaml
> -      - 8083:8080 # REST
а почему больше нет `rest` порта?

2021-11-18 18:43 UTC, LiFeAiR commented on docker-compose.yaml
> +  # pypiserver:
зачем закоментила?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/api/create_product.go
> +	metrics.AddCUDEvent(1, recommendation.Created)
`Добавить создание спанов для ручек`
это просто нигде не делала?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/api/describe_product.go
> +	logger.InfoKV(ctx, "DescribeProductV1 start")
тут не надо `metrics.AddCUDEvent`?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/api/list_product.go
> -		log.Debug().Msg("Internships not found")
тут не нало `metrics.AddIDNotFoundCall(1)`?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/pkg/middleware/logger_level.go
> +				logger.InfoKV(ctx, "New logger parce", "level", parsedLevel)
`New logger parsed`?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/repo/event.go
> +	defer span.Finish()
`span` больше ни где не используется?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/repo/event.go
> +	defer span.Finish()
чуть ниже err можно тоже залогировать и для него использовать этот `ctx`

2021-11-18 18:43 UTC, LiFeAiR commented on internal/repo/repo.go
> +		if rbErr := tx.Rollback(); rbErr != nil {
прогони весь код через `go fmt ./...`
вдруг это еще где то есть

2021-11-18 18:43 UTC, LiFeAiR commented on internal/repo/repo.go
>  			log.Error().Err(rbErr)
а почему тут не `logger.DebugKV(ctx,`?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/server/gatawey.go
> +		//grpc.WithUnaryInterceptor(
почему закомментировано?

2021-11-18 18:43 UTC, LiFeAiR commented on internal/tracer/tracer.go
> +func NewTracer(ctx context.Context, serviceName string, host string, port string) (io.Closer, error) {
была циклическая зависимость?

2021-11-18 18:51 UTC, MariaSopkova commented on internal/api/describe_product.go
> +	logger.InfoKV(ctx, "DescribeProductV1 start")
Это не не CUD. А просто получение данных. Я решила что нет :)

2021-11-18 18:55 UTC, MariaSopkova commented on docker-compose.yaml
> -      - 8083:8080 # REST
Верну :)

2021-11-18 18:56 UTC, MariaSopkova commented on docker-compose.yaml
> +  # pypiserver:
Я его не использую сейчас. А когда поднимаю в докере, он память отжирает, а у меня и так ее не много :( Верну потом

2021-11-18 18:58 UTC, MariaSopkova commented on internal/api/list_product.go
> -		log.Debug().Msg("Internships not found")
Опять же. Я посчитала что AddIDNotFoundCall это когда мы хотим сделать CUD события по id, которого нет

2021-11-18 19:00 UTC, MariaSopkova commented on internal/pkg/middleware/logger_level.go
> +				logger.InfoKV(ctx, "New logger parce", "level", parsedLevel)
Я очень грамотная :)

2021-11-18 19:01 UTC, MariaSopkova commented on internal/repo/event.go
> +	defer span.Finish()
Нет. А этого не достаточно?

2021-11-18 19:04 UTC, MariaSopkova commented on internal/repo/event.go
> +	defer span.Finish()
отличная идея

2021-11-18 19:05 UTC, MariaSopkova commented on internal/repo/repo.go
>  			log.Error().Err(rbErr)
Не заметила

2021-11-18 19:07 UTC, MariaSopkova commented on internal/tracer/tracer.go
> +func NewTracer(ctx context.Context, serviceName string, host string, port string) (io.Closer, error) {
Вроде нет. Аргумент что мне так больше нравится не прокатит? :) Если это хуже, чем первый вариант - я верну обратно

2021-11-21 19:31 UTC, LiFeAiR commented on internal/tracer/tracer.go
> +func NewTracer(ctx context.Context, serviceName string, host string, port string) (io.Closer, error) {
да, первый вариант был лучше

2021-11-21 19:34 UTC, LiFeAiR commented on internal/repo/repo.go
>  				log.Error().Err(rbErr)
все `log.Error()` замени на `logger.ErrorKV(ctx`

2021-11-23 17:17 UTC, LiFeAiR approved these changes

2021-11-28 14:12 UTC, merged