Task/feature 6
ozonmp/rcn-product-api pull request #5
Opened 2021-11-24 19:37 UTC by MariaSopkova

2021-11-27 01:00 UTC, LiFeAiR commented
в таком большем комитете лучше все задачи на алмаз помечать комментариями
чтобы было видно где они реализованы..

2021-11-27 01:01 UTC, LiFeAiR requested changes

2021-11-27 21:06 UTC, MariaSopkova commented on internal/repo/event.go
> +//type eventProduct pb.EventProduct
Вынесла код в другой файл. Тут удалила

2021-11-28 17:37 UTC, LiFeAiR approved these changes

2021-11-29 07:45 UTC, merged